CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_organizations_slug UNIQUE (slug),
    CONSTRAINT ck_organizations_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    platform_role VARCHAR(20) NOT NULL DEFAULT 'CANDIDATE',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_platform_role CHECK (platform_role IN ('PLATFORM_ADMIN', 'CANDIDATE'))
);

CREATE TABLE org_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organizations (id),
    user_id BIGINT NOT NULL REFERENCES users (id),
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_org_members_org_user UNIQUE (org_id, user_id),
    CONSTRAINT ck_org_members_role CHECK (role IN ('ORG_ADMIN', 'RECRUITER'))
);
CREATE INDEX idx_org_members_user ON org_members (user_id);

CREATE TABLE candidate_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users (id),
    phone VARCHAR(20),
    location VARCHAR(200),
    headline VARCHAR(250),
    total_experience_months INT,
    seeking_status VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_candidate_seeking_status
        CHECK (seeking_status IN ('ACTIVELY_LOOKING', 'OPEN_TO_OFFERS', 'NOT_LOOKING'))
);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_skills_name_lower ON skills (LOWER (name));

CREATE TABLE candidate_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    skill_id BIGINT NOT NULL REFERENCES skills (id),
    source VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_candidate_skills UNIQUE (user_id, skill_id),
    CONSTRAINT ck_candidate_skills_source CHECK (source IN ('RESUME_PARSED', 'SELF_DECLARED'))
);
CREATE INDEX idx_candidate_skills_skill ON candidate_skills (skill_id);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organizations (id),
    created_by BIGINT NOT NULL REFERENCES users (id),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    department VARCHAR(120),
    location VARCHAR(200),
    employment_type VARCHAR(20) NOT NULL DEFAULT 'FULL_TIME',
    experience_min_months INT NOT NULL DEFAULT 0,
    experience_max_months INT,
    salary_min NUMERIC(12, 2),
    salary_max NUMERIC(12, 2),
    currency CHAR(3),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_jobs_employment_type
        CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP')),
    CONSTRAINT ck_jobs_status CHECK (status IN ('DRAFT', 'OPEN', 'PAUSED', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_jobs_experience_range CHECK (
        experience_max_months IS NULL
        OR experience_max_months >= experience_min_months
    ),
    CONSTRAINT ck_jobs_salary_range CHECK (
        salary_min IS NULL
        OR salary_max IS NULL
        OR salary_max >= salary_min
    )
);
CREATE INDEX idx_jobs_org_status ON jobs (org_id, status);

CREATE TABLE job_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills (id),
    requirement VARCHAR(12) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_job_skills UNIQUE (job_id, skill_id),
    CONSTRAINT ck_job_skills_requirement CHECK (requirement IN ('MANDATORY', 'PREFERRED'))
);
CREATE INDEX idx_job_skills_skill ON job_skills (skill_id);

CREATE TABLE resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    storage_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UPLOADED',
    parse_error TEXT,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    parsed_at TIMESTAMPTZ,
    CONSTRAINT uq_resumes_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_resumes_status CHECK (status IN ('UPLOADED', 'PARSING', 'PARSED', 'FAILED'))
);
CREATE INDEX idx_resumes_user ON resumes (user_id);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs (id),
    user_id BIGINT NOT NULL REFERENCES users (id),
    resume_id BIGINT NOT NULL REFERENCES resumes (id),
    match_percentage NUMERIC(5, 2),
    score_details JSONB,
    ai_summary TEXT,
    status VARCHAR(25) NOT NULL DEFAULT 'APPLIED',
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_applications_user_job UNIQUE (user_id, job_id),
    CONSTRAINT ck_applications_status CHECK (
        status IN ('APPLIED', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'SELECTED', 'REJECTED', 'WITHDRAWN')
    )
);
CREATE INDEX idx_applications_job ON applications (job_id);
CREATE INDEX idx_applications_user ON applications (user_id);

CREATE TABLE skill_gap_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications (id),
    missing_mandatory JSONB NOT NULL DEFAULT '[]'::jsonb,
    missing_preferred JSONB NOT NULL DEFAULT '[]'::jsonb,
    recommendations JSONB NOT NULL DEFAULT '[]'::jsonb,
    generated_by VARCHAR(15) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_skill_gap_reports_application UNIQUE (application_id),
    CONSTRAINT ck_skill_gap_generated_by CHECK (generated_by IN ('RULE_BASED', 'AI'))
);

CREATE TABLE interview_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    category VARCHAR(15) NOT NULL,
    question_text TEXT NOT NULL,
    answer_guidance TEXT,
    source VARCHAR(15) NOT NULL,
    is_edited BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_interview_questions_category
        CHECK (category IN ('TECHNICAL', 'HR', 'BEHAVIORAL', 'SCENARIO', 'CODING')),
    CONSTRAINT ck_interview_questions_source
        CHECK (source IN ('AI_GENERATED', 'TEMPLATE', 'HUMAN'))
);
CREATE INDEX idx_interview_questions_application ON interview_questions (application_id);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    type VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    payload JSONB,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_notifications_type CHECK (
        type IN (
            'REGISTRATION',
            'RESUME_UPLOADED',
            'APPLICATION_RECEIVED',
            'APPLICATION_SHORTLISTED',
            'APPLICATION_REJECTED',
            'INTERVIEW_SCHEDULED',
            'SELECTION',
            'PASSWORD_RESET'
        )
    )
);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT REFERENCES organizations (id),
    actor_user_id BIGINT REFERENCES users (id),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id BIGINT,
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_logs_org_time ON audit_logs (org_id, created_at DESC);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

CREATE TABLE email_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL,
    purpose VARCHAR(25) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_email_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_email_tokens_purpose
        CHECK (purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'RECRUITER_INVITE'))
);

CREATE TABLE course_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id BIGINT REFERENCES skills (id),
    title VARCHAR(250) NOT NULL,
    provider VARCHAR(120) NOT NULL,
    url VARCHAR(500) NOT NULL,
    kind VARCHAR(15) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_course_resources_kind
        CHECK (kind IN ('COURSE', 'CERTIFICATION', 'DOC', 'TUTORIAL'))
);
CREATE INDEX idx_course_resources_skill ON course_resources (skill_id);
