-- Seeds the canonical skills catalog used by resume parsing and job requirements.
INSERT INTO skills (name, category) VALUES
    ('Java', 'Programming'),
    ('Python', 'Programming'),
    ('JavaScript', 'Programming'),
    ('TypeScript', 'Programming'),
    ('Go', 'Programming'),
    ('Rust', 'Programming'),
    ('Kotlin', 'Programming'),
    ('Ruby', 'Programming'),
    ('PHP', 'Programming'),
    ('Swift', 'Programming'),
    ('Scala', 'Programming'),
    ('C#', 'Programming'),
    ('C++', 'Programming'),
    ('SQL', 'Programming'),
    ('HTML', 'Frontend'),
    ('CSS', 'Frontend'),
    ('React', 'Frontend'),
    ('Angular', 'Frontend'),
    ('Vue', 'Frontend'),
    ('Next.js', 'Frontend'),
    ('Redux', 'Frontend'),
    ('Tailwind CSS', 'Frontend'),
    ('Bootstrap', 'Frontend'),
    ('jQuery', 'Frontend'),
    ('Spring Boot', 'Backend'),
    ('Spring', 'Backend'),
    ('Node.js', 'Backend'),
    ('Express', 'Backend'),
    ('Django', 'Backend'),
    ('Flask', 'Backend'),
    ('ASP.NET', 'Backend'),
    ('Laravel', 'Backend'),
    ('Rails', 'Backend'),
    ('GraphQL', 'Backend'),
    ('REST', 'Backend'),
    ('Microservices', 'Backend'),
    ('Hibernate', 'Backend'),
    ('Kafka', 'Data Engineering'),
    ('RabbitMQ', 'Data Engineering'),
    ('PostgreSQL', 'Databases'),
    ('MySQL', 'Databases'),
    ('MongoDB', 'Databases'),
    ('Redis', 'Databases'),
    ('Oracle Database', 'Databases'),
    ('SQL Server', 'Databases'),
    ('Elasticsearch', 'Databases'),
    ('DynamoDB', 'Databases'),
    ('Cassandra', 'Databases'),
    ('Firebase', 'Databases'),
    ('AWS', 'Cloud & DevOps'),
    ('Azure', 'Cloud & DevOps'),
    ('Google Cloud', 'Cloud & DevOps'),
    ('Docker', 'Cloud & DevOps'),
    ('Kubernetes', 'Cloud & DevOps'),
    ('Terraform', 'Cloud & DevOps'),
    ('Jenkins', 'Cloud & DevOps'),
    ('Git', 'Cloud & DevOps'),
    ('CI/CD', 'Cloud & DevOps'),
    ('Linux', 'Cloud & DevOps'),
    ('Ansible', 'Cloud & DevOps'),
    ('Prometheus', 'Cloud & DevOps'),
    ('Grafana', 'Cloud & DevOps'),
    ('GitHub Actions', 'Cloud & DevOps'),
    ('Machine Learning', 'AI & Data'),
    ('Deep Learning', 'AI & Data'),
    ('Natural Language Processing', 'AI & Data'),
    ('Computer Vision', 'AI & Data'),
    ('Pandas', 'AI & Data'),
    ('NumPy', 'AI & Data'),
    ('TensorFlow', 'AI & Data'),
    ('PyTorch', 'AI & Data'),
    ('Scikit-learn', 'AI & Data'),
    ('Apache Spark', 'AI & Data'),
    ('Hadoop', 'AI & Data'),
    ('Power BI', 'Analytics'),
    ('Tableau', 'Analytics'),
    ('Excel', 'Analytics'),
    ('Looker', 'Analytics'),
    ('Selenium', 'Testing'),
    ('Cypress', 'Testing'),
    ('Playwright', 'Testing'),
    ('JUnit', 'Testing'),
    ('Mockito', 'Testing'),
    ('TestNG', 'Testing'),
    ('Appium', 'Testing'),
    ('Maven', 'Tooling'),
    ('Gradle', 'Tooling'),
    ('IntelliJ IDEA', 'Tooling'),
    ('VS Code', 'Tooling'),
    ('Postman', 'Tooling'),
    ('Figma', 'Tooling'),
    ('Jira', 'Tooling'),
    ('Confluence', 'Tooling'),
    ('Bitbucket', 'Tooling'),
    ('GitLab', 'Tooling'),
    ('Agile', 'Practices'),
    ('Scrum', 'Practices'),
    ('Kanban', 'Practices'),
    ('TDD', 'Practices'),
    ('BDD', 'Practices'),
    ('System Design', 'Practices'),
    ('Data Structures', 'Practices'),
    ('Algorithms', 'Practices'),
    ('OOP', 'Practices'),
    ('Communication', 'Soft Skills'),
    ('Leadership', 'Soft Skills'),
    ('Teamwork', 'Soft Skills'),
    ('Problem Solving', 'Soft Skills'),
    ('Time Management', 'Soft Skills'),
    ('Mentoring', 'Soft Skills');

